
import { PracticeSession, PricingPlan } from '../types';

/**
 * Constructs and triggers a WhatsApp notification to the admin
 * with full details of a new successful booking.
 */
export const sendAdminWhatsAppNotification = (session: PracticeSession, plan: PricingPlan) => {
  const adminNumber = "2349029729621";
  
  const examSpecs = session.natureOfPractice === 'Exam' 
    ? `\n- Question Type: ${session.questionType}\n- Standard: ${session.examStandard}`
    : `\n- Preference: ${session.genderPreference}`;

  const message = `*🔥 New Meditin Registration!*
----------------------------
*Client:* ${session.fullName}
*Email:* ${session.email}
*Sector:* ${session.sector}
*Field:* ${session.field}
*Nature:* ${session.natureOfPractice}${examSpecs}
*Schedule:* ${session.date} @ ${session.time}
*Plan:* ${plan.name} (₦${plan.price.toLocaleString()})
----------------------------
_Generated by Meditin Booking System_`;

  const encodedMessage = encodeURIComponent(message);
  const whatsappUrl = `https://wa.me/${adminNumber}?text=${encodedMessage}`;
  
  // We open this in a new tab so it doesn't interrupt the user's flow
  window.open(whatsappUrl, '_blank');
};
