
import { PracticeSession, PricingPlan } from '../types';

/**
 * Constructs and triggers a WhatsApp notification to the admin
 * with full details of a new successful booking or waiting list entry.
 */
export const sendAdminWhatsAppNotification = (session: PracticeSession, plan: PricingPlan, isWaitingList: boolean = false) => {
  const adminNumber = "2349029729621";
  
  const statusHeader = isWaitingList 
    ? "⏳ NEW WAITING LIST LEAD (15% OFF)" 
    : "🔥 NEW ACTIVE REGISTRATION";

  const finalPrice = isWaitingList ? Math.round(plan.price * 0.85) : plan.price;

  const examSpecs = session.natureOfPractice === 'Exam' 
    ? `\n- Question Type: ${session.questionType}\n- Standard: ${session.examStandard}`
    : `\n- Preference: ${session.genderPreference}`;

  const message = `*${statusHeader}*
----------------------------
*Client:* ${session.fullName}
*Email:* ${session.email}
*Sector:* ${session.sector}
*Field:* ${session.field}
*Type:* ${session.applicationType || 'Professional'}
*Nature:* ${session.natureOfPractice}${examSpecs}
*Schedule:* ${session.date} @ ${session.time}
*Selected Plan:* ${plan.name}
*Original Price:* ₦${plan.price.toLocaleString()}
*Promised Total:* ₦${finalPrice.toLocaleString()}
*Lead Intent:* ${isWaitingList ? 'WAITING FOR INVOICE' : 'READY TO PAY'}
----------------------------
_Generated by Meditin Intel Engine_`;

  const encodedMessage = encodeURIComponent(message);
  const whatsappUrl = `https://wa.me/${adminNumber}?text=${encodedMessage}`;
  
  // We open this in a new tab so it doesn't interrupt the user's flow
  window.open(whatsappUrl, '_blank');
};